// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Top5.Data;

#nullable disable

namespace Top5.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260223014440_addisRevoked")]
    partial class addisRevoked
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Top5.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Teamid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("awayScore")
                        .HasColumnType("int");

                    b.Property<Guid>("awayTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("homeScore")
                        .HasColumnType("int");

                    b.Property<Guid>("homeTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isComptitve")
                        .HasColumnType("bit");

                    b.Property<DateTime>("kickOff")
                        .HasColumnType("datetime2");

                    b.Property<string>("matchFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("statues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("id");

                    b.HasIndex("Teamid");

                    b.HasIndex("awayTeamId");

                    b.HasIndex("homeTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Top5.Domain.Entities.MatchPlayers", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("assists")
                        .HasColumnType("int");

                    b.Property<int>("goals")
                        .HasColumnType("int");

                    b.Property<Guid>("matchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("playerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("rate")
                        .HasColumnType("float");

                    b.Property<int>("saves")
                        .HasColumnType("int");

                    b.Property<Guid>("teamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("matchId");

                    b.HasIndex("playerId");

                    b.HasIndex("teamId");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("Top5.Domain.Entities.SysSetting", b =>
                {
                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PitchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SysSettings");
                });

            modelBuilder.Entity("Top5.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<Guid>("captinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("goals")
                        .HasColumnType("int");

                    b.Property<int>("goalsAgainest")
                        .HasColumnType("int");

                    b.Property<int>("loses")
                        .HasColumnType("int");

                    b.Property<int>("matchCount")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("points")
                        .HasColumnType("int");

                    b.Property<int>("wins")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("captinId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Top5.Domain.Entities.TeamPlayers", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("playerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("teamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("playerId");

                    b.HasIndex("teamId");

                    b.ToTable("TeamPlayers");
                });

            modelBuilder.Entity("Top5.Domain.Entities.Token", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("expiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("hashedToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isRevoked")
                        .HasColumnType("bit");

                    b.Property<Guid>("playerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("revokedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("playerId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Top5.Domain.Models.Player", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("dob")
                        .HasColumnType("date");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("position")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Top5.Domain.Entities.Match", b =>
                {
                    b.HasOne("Top5.Domain.Entities.Team", null)
                        .WithMany("Matches")
                        .HasForeignKey("Teamid");

                    b.HasOne("Top5.Domain.Entities.Team", "awayTeam")
                        .WithMany()
                        .HasForeignKey("awayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Top5.Domain.Entities.Team", "homeTeam")
                        .WithMany()
                        .HasForeignKey("homeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("awayTeam");

                    b.Navigation("homeTeam");
                });

            modelBuilder.Entity("Top5.Domain.Entities.MatchPlayers", b =>
                {
                    b.HasOne("Top5.Domain.Entities.Match", "match")
                        .WithMany()
                        .HasForeignKey("matchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Top5.Domain.Models.Player", "player")
                        .WithMany()
                        .HasForeignKey("playerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Top5.Domain.Entities.Team", "team")
                        .WithMany()
                        .HasForeignKey("teamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("match");

                    b.Navigation("player");

                    b.Navigation("team");
                });

            modelBuilder.Entity("Top5.Domain.Entities.Team", b =>
                {
                    b.HasOne("Top5.Domain.Models.Player", "captin")
                        .WithMany()
                        .HasForeignKey("captinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("captin");
                });

            modelBuilder.Entity("Top5.Domain.Entities.TeamPlayers", b =>
                {
                    b.HasOne("Top5.Domain.Models.Player", "player")
                        .WithMany()
                        .HasForeignKey("playerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Top5.Domain.Entities.Team", "team")
                        .WithMany()
                        .HasForeignKey("teamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("player");

                    b.Navigation("team");
                });

            modelBuilder.Entity("Top5.Domain.Entities.Token", b =>
                {
                    b.HasOne("Top5.Domain.Models.Player", "player")
                        .WithMany()
                        .HasForeignKey("playerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("player");
                });

            modelBuilder.Entity("Top5.Domain.Entities.Team", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
